### ISSUE TITLE
Research for Angular Material

### ISSUE THREAD

**Issue by PrarabdhJoshi** [PrarabdhJoshi/evep_mapUI#2]
@BharathAlva Please run a research on **angular material** and try implementing a **Search/Map based UI** using it. Something like this would be nice:

https://www.tapingo.com/order/near/?coordinates=29.6130239,-82.371937&service=pickup&str=Gainesville%2C%20FL%2032611%2C%20USA

with some obvious variations. Thanks!

**Comment by BharathAlva** [comment]
Template done using Angular Material.... Map rendering is still a problem and is raised in another issue.
